//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstaccount
    {
        public long Id { get; set; }
        public long AddressId { get; set; }
        public string Username { get; set; }
        public string EncryptionMethod { get; set; }
        public string KeyScheme { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public string BPN { get; set; }
        public string TIN { get; set; }
        public string AccountType { get; set; }
        public string TimeRegion { get; set; }
        public Nullable<System.DateTime> IsCreatedOn { get; set; }
        public Nullable<System.DateTime> IsUpdatedOn { get; set; }
        public Nullable<sbyte> IsSuspended { get; set; }
        public Nullable<System.DateTime> IsSuspendedOn { get; set; }
        public Nullable<System.DateTime> SuspensionEndsOn { get; set; }
        public Nullable<sbyte> IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveOn { get; set; }
        public Nullable<sbyte> IsPrivate { get; set; }
        public Nullable<sbyte> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
    }
}
