//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstaccount_activitylog
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public string LinkVisited { get; set; }
        public string DeviceDetails { get; set; }
        public string BrowserDetails { get; set; }
        public string Ipv4Address { get; set; }
        public string Ipv6Address { get; set; }
        public Nullable<System.DateTime> VisitedOn { get; set; }
        public Nullable<System.TimeSpan> TimeSpent { get; set; }
    }
}
