//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstcompetition
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public Nullable<long> GameId { get; set; }
        public string CompetitionName { get; set; }
        public string Description { get; set; }
        public string MetaDescription { get; set; }
        public string CompetitionModel { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> EntryPrice { get; set; }
        public Nullable<int> TeamSize { get; set; }
        public Nullable<int> MaxNoOfTeams { get; set; }
        public Nullable<int> TeamsRegistered { get; set; }
        public Nullable<decimal> TotalPrizeMoney { get; set; }
        public Nullable<long> FirstPlaceId { get; set; }
        public Nullable<long> SecondPlaceId { get; set; }
        public Nullable<long> ThirdPlaceId { get; set; }
        public Nullable<long> FourthPlaceId { get; set; }
        public Nullable<long> FifthPlaceId { get; set; }
        public Nullable<long> SixthPlaceId { get; set; }
        public Nullable<long> SeventhPlaceId { get; set; }
        public Nullable<long> EigthPlaceId { get; set; }
        public Nullable<long> NinthPlaceId { get; set; }
        public Nullable<long> TenthPlaceId { get; set; }
        public Nullable<decimal> FirstPlaceReward { get; set; }
        public Nullable<decimal> SecondPlaceReward { get; set; }
        public Nullable<decimal> ThirdPlaceReward { get; set; }
        public Nullable<decimal> FourthPlaceReward { get; set; }
        public Nullable<decimal> FifthPlaceReward { get; set; }
        public Nullable<decimal> SixthPlaceReward { get; set; }
        public Nullable<decimal> SeventhPlaceReward { get; set; }
        public Nullable<decimal> EigthPlaceReward { get; set; }
        public Nullable<decimal> NinthPlaceReward { get; set; }
        public Nullable<decimal> TenthPlaceReward { get; set; }
        public Nullable<long> Likes { get; set; }
        public Nullable<long> Views { get; set; }
        public Nullable<long> Shares { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
