//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstcourses_tests
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public long CourseId { get; set; }
        public string Title { get; set; }
        public sbyte Format { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public sbyte RandomizeOrder { get; set; }
        public sbyte NumQuestions { get; set; }
        public string Instructions { get; set; }
        public long ContentId { get; set; }
        public sbyte ResultRelease { get; set; }
        public sbyte Difficulty { get; set; }
        public sbyte NumTakes { get; set; }
        public string Description { get; set; }
        public int PassScore { get; set; }
        public int PassPercent { get; set; }
        public string PassFeedback { get; set; }
        public string FailFeedback { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
