//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstcampaign
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Category { get; set; }
        public string Location { get; set; }
        public Nullable<bool> CampaignStatus { get; set; }
        public Nullable<decimal> ExpectedRevenue { get; set; }
        public Nullable<decimal> BudgetCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public string ExpectedResponse { get; set; }
        public Nullable<int> NumberSent { get; set; }
        public string Sponsor { get; set; }
        public string TargetAudience { get; set; }
        public Nullable<int> TargetSize { get; set; }
        public Nullable<int> ExpectedResponseCount { get; set; }
        public Nullable<int> ExpectedSalesCount { get; set; }
        public Nullable<decimal> ExpectedROI { get; set; }
        public Nullable<int> ActualResponseCount { get; set; }
        public Nullable<int> ActualSalesCount { get; set; }
        public Nullable<decimal> ActualROI { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<long> Likes { get; set; }
        public Nullable<long> Views { get; set; }
        public Nullable<long> Shares { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
