//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstfiles_pdf
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public string Generator { get; set; }
        public string ModuleName { get; set; }
        public string HeaderContent { get; set; }
        public string BodyContent { get; set; }
        public string FooterContent { get; set; }
        public bool Status { get; set; }
        public string PrimaryName { get; set; }
        public string SecondaryName { get; set; }
        public string MetaAuthor { get; set; }
        public string MetaKeywords { get; set; }
        public bool MetatagsStatus { get; set; }
        public string MetaSubject { get; set; }
        public string MetaTitle { get; set; }
        public string PageFormat { get; set; }
        public Nullable<bool> MarginChkbox { get; set; }
        public Nullable<short> MarginTop { get; set; }
        public Nullable<short> MarginBottom { get; set; }
        public Nullable<short> MarginLeft { get; set; }
        public Nullable<short> MarginRight { get; set; }
        public Nullable<short> HeaderHeight { get; set; }
        public Nullable<short> FooterHeight { get; set; }
        public string PageOrientation { get; set; }
        public string Language { get; set; }
        public string FileName { get; set; }
        public string Visibility { get; set; }
        public Nullable<bool> Default { get; set; }
        public string Conditions { get; set; }
        public bool WatermarkType { get; set; }
        public string WatermarkText { get; set; }
        public short WatermarkAngle { get; set; }
        public string WatermarkImage { get; set; }
        public string TemplateMembers { get; set; }
        public Nullable<bool> OnePdf { get; set; }
        public Nullable<bool> Type { get; set; }
        public string Styles { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
