//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstproducts_transactions
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public long SenderId { get; set; }
        public long ReceiverId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string TypeOfTransaction { get; set; }
        public string TransactionDetails { get; set; }
        public string PaymentMethod { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReceiptNo { get; set; }
        public string Reason { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
