//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tstdealsv2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Web.Script.Serialization;


    public  partial class tstproduct
    {
        public long Id { get; set; }
        [ScriptIgnore]
        public long OwnerId { get; set; }
        public Nullable<long> StoreId { get; set; }
        public string ProductName { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaTitle { get; set; }
        public string Sku { get; set; }
        public string Gtin { get; set; }
        public Nullable<long> ProductTypeId { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<bool> AllowCustomerReviews { get; set; }
        public Nullable<long> ApprovedRatingSum { get; set; }
        public Nullable<long> NotApprovedRatingSum { get; set; }
        public Nullable<bool> IsGiftCard { get; set; }
        public Nullable<long> GiftCardTypeId { get; set; }
        public Nullable<decimal> OverriddenGiftCardAmount { get; set; }
        public Nullable<bool> IsDownload { get; set; }
        public Nullable<long> DownloadId { get; set; }
        public Nullable<bool> UnlimitedDownloads { get; set; }
        public Nullable<long> MaxNumberOfDownloads { get; set; }
        public Nullable<long> DownloadExpirationDays { get; set; }
        public Nullable<long> DownloadActivationTypeId { get; set; }
        public Nullable<bool> HasSampleDownload { get; set; }
        public Nullable<long> SampleDownloadId { get; set; }
        public Nullable<bool> HasUserAgreement { get; set; }
        public string UserAgreementText { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public Nullable<long> RecurringCycleLength { get; set; }
        public Nullable<long> RecurringCyclePeriodId { get; set; }
        public Nullable<long> RecurringTotalCycles { get; set; }
        public Nullable<bool> IsRental { get; set; }
        public Nullable<long> RentalPriceLength { get; set; }
        public Nullable<bool> IsTaxExempt { get; set; }
        public Nullable<long> TaxCategoryId { get; set; }
        public Nullable<long> StockQuantity { get; set; }
        public Nullable<long> MinStockQuantity { get; set; }
        public Nullable<bool> AllowBackInStockSubscriptions { get; set; }
        public Nullable<long> OrderMinimumQuantity { get; set; }
        public Nullable<long> OrderMaximumQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsDeleted { get; set; }
        [ScriptIgnore]
        public Nullable<bool> IsActive { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        [ScriptIgnore]
        public Nullable<System.DateTime> IsActiveOn { get; set; }
    }
}
